/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.poo_practica;

public class Main {
    public static void main(String[] args) {
        Coche coche1 = new Coche("Rojo", "Toyota", "Prado", 59.4, 30.5);
        // coche1.acelerar(40);
        System.out.println(coche1);

        coche1.peso = 40.0;
        System.out.println(coche1);

        CocheElectrico cocheElectrico1 = new CocheElectrico();

        cocheElectrico1.motorElectrico = "TX60";
        cocheElectrico1.color = "Azul";
        cocheElectrico1.fabricante = "Mercedez Benz";
        cocheElectrico1.modelo = "T560";

        System.out.println(cocheElectrico1);

        CocheElectrico cocheElectrico2 = new CocheElectrico("Verde", "Chevrolet", "Camaro", 70.5, 50.5, "TX40");
        System.out.println(cocheElectrico2);

        cocheElectrico2.acelerar(50);
        System.out.println(cocheElectrico2);

        CocheElectrico cocheElectrico3 = new CocheElectrico("TX30");

        cocheElectrico3.color = "Negro";
        cocheElectrico3.fabricante = "Buggatti";
        cocheElectrico3.modelo = "T280";

        System.out.println(cocheElectrico3);
    }
}
