/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package metodos_de_la_clase_string_practica;

public class Main {
    public static void main(String[] args) {
        /* 
         * lenght()
         * startsWith("")
         * endsWidth("")
         * indexOf("")
         * subString(1, 5)
         * trim()
         * equals()
         * compareTo
         */

        String mensaje = "\n  Hola Mundo  ";
        String mensajeMin = mensaje.toLowerCase();
        
        System.out.println(mensajeMin);
        System.out.println("Tamaño del string: " + mensajeMin.length());
        
        String mensajeTrim = mensajeMin.trim();
        System.out.println("\n" + mensajeTrim);
        System.out.println("Tamaño del string: " + mensajeTrim.length());

        String mensaje2 = "hola mundo";

        if (mensajeTrim.equals(mensaje2)) {
            System.out.println(mensajeTrim + " es igual a " + mensaje2 + "\n");
        } else {
            System.out.println(mensajeTrim + " es diferente de " + mensaje2 + "\n");
        }
    }
}
