/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prueba_java;

public class Main {
    public static void main(String[] args) {
        helloWorld("David");
    }

    public static void helloWorld(String nombre) {
        System.out.println("Hola " + nombre);
    }
}
